package com.recruitment.server.model;

public enum NotificationType {
    APPLICATION_RECEIVED,
    SCREENING_SCHEDULED,
    SCREENING_COMPLETED,
    INTERVIEW_SCHEDULED,
    INTERVIEW_COMPLETED,
    SELECTED,
    REJECTED,
    OFFER_GENERATED,
    OFFER_ACCEPTED,
    DOCUMENT_VERIFICATION_PENDING,
    DOCUMENT_VERIFIED,
    JOINED,
    ON_HOLD,
    APPLICATION_UPDATED,
    SKILL_ASSESSMENT_PENDING,
    SKILL_ASSESSMENT_COMPLETED
}
